### ISSUE TITLE
False positives ? really ?

### ISSUE THREAD

**Issue by franktbc** [major/icanhaz#24]
so this domain will be blacklisted for ever, for simple reason that hackers use this to get the reverse or ip of the device they are hacking, i see you asked in a few forums to REMOVE this from that, but to be honest, its not a good idea.
You need to add API to identify WHO is using your service to do this, not doing so is not only dangerous, but puts everyone at risk.

personnally we block this and will forever since theres always a chance its from a ransomware or other malware asking for ip.
the fact we don't know WHAT asked for it, makes it impossible to get details.

at least if we could poll your site to ?debug=on, and would  show last requests from what calling app or device on the IP that pulls the request, that would be better.

icanhazip.com/?debug=1

would return 
IP, DATE, AGENT, PARAMS or PUBLIC API KEY

this way you could #1... be on top of your game, #2 protect the innocent.

**Comment by major** [comment]
> so this domain will be blacklisted for ever, for simple reason that hackers use this to get the reverse or ip of the device they are hacking, i see you asked in a few forums to REMOVE this from that, but to be honest, its not a good idea.
> You need to add API to identify WHO is using your service to do this, not doing so is not only dangerous, but puts everyone at risk.

I totally understand your sentiment here, but I don't collect access logs from visitors. First off, it's way too much data to manage with over seven billion requests per day. Also, I want to keep the server-side code as light as possible since I'm sponsored by CloudFlare and able to use their Workers service for free right now.

I've received lots of emails over the years from three letter agencies, corporate security teams, and security researchers. Many of them use the calls to icanhazip as indicators of compromise (IOC) and that data is useful for hunt teams who want to track down a compromise of a particular device. Blocking it entirely is a good idea, but you may lose out on some of the detail of how widespread your compromise truly is.

Either way, I wish you the best and I appreciate your note!
